CMWebApp-war/src/fit5042/cm/controllers/ContactController.java
package fit5042.cm.controllers;

import javax.el.ELContext;
import javax.inject.Named;
import javax.enterprise.context.Dependent;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;

/**
 *
 * @author Sunpreet Kaur
 */
@Named(value = "contactController")
@RequestScoped
public class ContactController {

    private int contactId; 

    public int getContactId() {
        return contactId;
    }

    public void setContactId(int contactId) {
        this.contactId = contactId;
    }
    
    private fit5042.cm.repository.entities.Contact contact;
    

    public ContactController() {
      
    	contactId = Integer.valueOf(FacesContext.getCurrentInstance()
                .getExternalContext()
                .getRequestParameterMap()
                .get("contactID"));
      
        contact = getContact();
    }

    public fit5042.cm.repository.entities.Contact getContact() {
        if (contact == null) {
            
            ELContext context
                    = FacesContext.getCurrentInstance().getELContext();
            ContactApplication app
                    = (ContactApplication) FacesContext.getCurrentInstance()
                            .getApplication()
                            .getELResolver()
                            .getValue(context, null, "contactApplication");
     
            return app.getContacts().get(--contactId); 
        }
        return contact;
    }
}

CMWebApp-war/src/fit5042/cm/mbeans/CustomerManagedBean.java
package fit5042.cm.mbeans;

import fit5042.cm.repository.CustomerRepository;
import fit5042.cm.repository.entities.Address;
import fit5042.cm.repository.entities.Contact;
import fit5042.cm.repository.entities.Customer;
import fit5042.cm.repository.entities.IndustryType;
import fit5042.cm.repository.entities.AppUser;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

/**
 *
 * @author Sunpreet Kaur
 * 
 */
@ManagedBean(name = "customerManagedBean")
@SessionScoped

public class CustomerManagedBean implements Serializable {

    @EJB
   CustomerRepository  customerRepository;

    
    public CustomerManagedBean() {
    }

    public List<Customer> getAllCustomers() {
        try {
            List<Customer> customers = customerRepository.getAllCustomers();
            return customers;
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
   public void addCustomer(Customer customer) 
    {
        try {
             customerRepository.addCustomer(customer);
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
   
    public Customer searchCustomerById(int id)
    {
        try {
            return customerRepository.searchCustomerById(id);
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return null;
    }
    
   
    public List<Customer> searchCustomerByName(String customerName)
    {
        try {
            return customerRepository.searchCustomerByName(customerName);
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return null;
    }
    public List<IndustryType> getAllIndustryType() {
    	 try {
             return customerRepository.getAllIndustryType();
         } catch (Exception ex) {
             Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
         }
       
        return null;
    }


    public void removeCustomer(int customerId) 
    {
        try {
            customerRepository.removeCustomer(customerId);
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void editCustomer(Customer customer)
    {
        try {
          
            
            customerRepository.editCustomer(customer);
            
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Customer has been updated succesfully"));
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public List<Customer> searchCustomerByNoOfProductPurchased(int noOfProductsPurchased)
    {
        try {
            return customerRepository.searchCustomerByNoOfProductPurchased(noOfProductsPurchased);
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return null;
    }

    public void addCustomer(fit5042.cm.controllers.Customer localCustomer) {
       
    	Customer customer = convertCustomerToEntity(localCustomer);
    	
    	

        try {
            customerRepository.addCustomer(customer);
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   
    private Customer convertCustomerToEntity(fit5042.cm.controllers.Customer localCustomer) {
    	Customer customer = new Customer(); 
    	
    	customer.setCustomerId(localCustomer.getCustomerId());
        customer.setName(localCustomer.getName());
        customer.setPhoneNo(localCustomer.getPhoneNo());
        customer.setEmail(localCustomer.getEmail());
        customer.setNoOfProductsPurchased(localCustomer.getNoOfProductsPurchased());
        customer.setRegisteredOn(localCustomer.getRegisteredOn());
        customer.setRegisteredBy(localCustomer.getRegisteredBy());

        customer.setIndustryType(localCustomer.getIndustryType());
        customer.setCustomerAssignedTo(localCustomer.getCustomerAssignedTo());

        String streetNumber = localCustomer.getStreetNumber();
        String streetAddress = localCustomer.getStreetAddress();
        String suburb = localCustomer.getSuburb();
        String postcode = localCustomer.getPostcode();
        String state = localCustomer.getState();
        Address address = new Address(streetNumber, streetAddress, suburb, postcode, state);
        customer.setAddress(address);
      
        customer.setIndustryTypeName(localCustomer.getIndustryTypeName());
     
         customer.setCustomerAssignee(localCustomer.getCustomerAssignee());
         return customer;
    }
  

}

CMWebApp-war/WebContent/403.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
	<h:head>
		<title>Index page</title>
	</h:head> 
	<body> 
		<h1>Sorry, you don't have access to this area</h1>
	</body> 
</html>

CMWebApp-war/WebContent/contactedit.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"      
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <title>#{titleController.pageTitle}</title> 
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    #{titleController.pageTitle} - Edit Contact Details
                </div>
            </div>

            <h:form id="MyForm">
                <table class="table table-bordered ">

                    <tr>
                        <td width ="200" valign="top">Id:</td>
                        
                        <td valign="bottom">
                            <h:outputLabel id = "Id" >#{contactController.contact.contactId}</h:outputLabel>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="200" valign="top"> Name: </td>
                     
                        <td valign="bottom">
                            <h:inputText id = "Name" value="#{contactController.contact.name}" binding="#{name}" required="true"
                                         validatorMessage="Please enter a valid contact name"
                                         requiredMessage="Please enter a contact name "></h:inputText>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="200" valign="top">Phone number: </td>
                     
                        <td valign="bottom">
                            <h:inputText id = "PhoneNo" value="#{contactController.contact.phoneNo}" binding="#{phoneNo}" required="true"
                                         validatorMessage="Please enter a valid phone number"
                                         requiredMessage="Please enter a phone number "></h:inputText>    
                        </td>
                    </tr>
                     <tr>
                        <td width ="200" valign="top">Email: </td>
                     
                        <td valign="bottom">
                            <h:inputText id = "Email" value="#{contactController.contact.email}" binding="#{email}" required="true"
                                         validatorMessage="Please enter a valid email address"
                                         requiredMessage="Please enter a email address "></h:inputText>    
                        </td>
                    </tr>
                    
                     
                    <tr>
                        <td width ="200" valign="top">Contact Role: </td>
                     
                        <td valign="bottom">
                            <h:inputText id = "Role" value="#{contactController.contact.role}" binding="#{role}" required="true"
                                         validatorMessage="Please enter a valid contact role"
                                         requiredMessage="Please enter a contact's role in customer company "></h:inputText>    
                        </td>
                    </tr>
           
                                      
                </table>
                
                <h:commandButton id="save" value="Save" action="#{contactManagedBean.editContact(contactController.contact)}"  class="btn btn-primary" >
                    <f:param name="customerID" value="#{contactController.contactId+1}"/>
                </h:commandButton>
                 &nbsp;
                <h:link id="close" value="Close" outcome="faces/contacts.xhtml"
						class="btn btn-primary" />
            </h:form>
        </div>
    </h:body>
</html>

CMWebApp-war/WebContent/contacts.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <title>#{titleController.pageTitle}</title>
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <!-- Title Customer Management-->
                <div class="navbar-brand">
                    #{titleController.pageTitle} - Contact List
                </div>
            </div>
            
            <h:form id="MyForm">
                <table class="table table-bordered table-striped">
                    <!-- For each customer in customers ArrayList... -->
                    <tr>
                            <td>
                                <h:outputLabel id="ContactId" value="Contact Id"  />
                            </td>
                            <td>
                                <h:outputLabel id="Name" value="Name"  />
                            </td>
                            <td>
                                <h:outputLabel id="Email" value="Email"/>
                            </td>
                            <td>
                                <h:outputLabel id="Role" value="Role"  />
                            </td>
                     </tr>

                    <ui:repeat id="Myrepeat" value="#{contactApplication.contacts}"  var="contact" varStatus="status">
                        <tr onclick="document.getElementById('MyForm:principle').value = document.getElementById('MyForm:Myrepeat:#{status.index}:contactId').textContent">
                            <td>
                                <h:outputText value="#{contactApplication.contacts.get(status.index).contactId}" id="contactId" />
                            </td>
                            <td>
                                <h:outputText id="outName" value="#{contactApplication.contacts.get(status.index).name}"  />
                            </td>
                            <td>
                                <h:outputText id="outEmail" value="#{contactApplication.contacts.get(status.index).email}"></h:outputText>
                            </td>
                            <td>
                                <h:outputText id="outRole" value="#{contactApplication.contacts.get(status.index).role}"  />
                            </td>
                            <td>
                                <h:link value="View | " outcome="faces/contactdetails.xhtml">
                               
                                  <f:param name="contactID" value="#{status.index + 1}"/>
                                </h:link>

                                <h:link value="Edit | " outcome="faces/contactedit.xhtml">
                               
                                  <f:param name="contactID" value="#{status.index + 1}"/>
                                </h:link>

                                <h:commandLink value="Delete" action="#{removeContact.removeContact(contactApplication.contacts.get(status.index).contactId)}" disabled="#{contactApplication.contacts.get(status.index).contactId == null}">
                                </h:commandLink>
                                

                                <h:outputText value=" "/>
                            </td>
                              
                        </tr>

                    </ui:repeat>

                </table>
                <div>
                    <h:commandButton id="add" value="Add" action="contactadd.xhtml" class="btn btn-primary" />
                      &nbsp;
                    <h:commandButton id="viewAll" value="View All" action="#{searchContact.searchAll()}" class="btn btn-primary" >
                        <f:param name="contactID" value="#{status.index + 1}"/>
                    </h:commandButton>
                </div>
                
                 <div>
                    <h:inputText value="#{searchContact.searchByInt}" id="searchById" required="true" onchange ="if (document.getElementById('MyForm:searchById').value.trim() == '') {document.getElementById('MyForm:searchById').value = 0;} "   />
                    <h:commandButton id="searchContactId" value="Search by Contact Id" action="#{searchContact.searchContactById(searchContact.searchByInt)}" class="btn btn-primary" >
                        <f:param name="contactID" value="#{status.index + 1}"/>
                    </h:commandButton>
                </div>
                  &nbsp;               
                 <div>
                    <h:inputText value="#{searchContact.searchByString}" id="searchByName" required="false" onchange ="if (document.getElementById('MyForm:searchByName').value.trim() == '') {document.getElementById('MyForm:searchByName').value = '';} "   />
                    <h:commandButton id="searchContactName" value="Search by Contact Name" action="#{searchContact.searchContactByName(searchContact.searchByString)}" class="btn btn-primary" >
                        <f:param name="contactID" value="#{status.index + 1}"/>  &nbsp;
                    </h:commandButton>
                </div>
              
                <br/>
		<h:link outcome="/customerindex" value="Go back to Customers Area" />
		<br/>
		<h:link outcome="/admin/index" value="Go back to User Area" />

               

            </h:form>
        </div>
    </h:body>
</html>

CMWebApp-war/WebContent/customeradd.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <h:outputStylesheet library="css" name="style.css"></h:outputStylesheet>
        <title>#{titleController.pageTitle}</title> 
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    #{titleController.pageTitle} - Add Customer
                </div>
            </div>
            <div>
        <f:view>
            <h:form>
               
                
                <table class="table table-bordered ">
                
              

                     <tr class="#{!customerName.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="Name:" for="customerName" />
                        </td>
                        <td>
                            <h:inputText id="customerName" value="#{customer.name}" title="customerName" required="true" requiredMessage="Please enter the customer name!" pt:placeholder="Australia and New Zealand Banking Group"/>
                            <br/>
                            <h:message for="customerName" class="#{!customerName.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    <tr class="#{!customerPhoneNo.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="Phone No:" for="customerPhoneNo" />
                        </td>
                        <td>
                            <h:inputText id="customerPhoneNo" value="#{customer.phoneNo}" title="customerPhoneNo" size = "10" required="true" requiredMessage="Please enter the customer phone number!" 
                            validatorMessage="Please enter a 10 digit phone number"
									converterMessage="Please enter a number"
									
									pt:placeholder="0468294739">
									<f:convertNumber integerOnly="true" /> </h:inputText>
                            <br/>
                            <h:message for="customerPhoneNo" class="#{!customerPhoneNo.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    <tr class="#{!customerEmail.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="Email:" for="customerEmail" />
                        </td>
                        <td>
                            <h:inputText id="customerEmail" value="#{customer.email}" title="customerEmail" required="true" requiredMessage="Please enter the customer email!" validatorMessage="Email entered for customer is not valid" pt:placeholder="anz@gmail.com">
                             <f:validateRegex pattern="[\w\.-]*[a-zA-Z0-9_]@[\w\.-]*[a-zA-Z0-9]\.[a-zA-Z][a-zA-Z\.]*[a-zA-Z]" /></h:inputText>
                            <br/>
                            <h:message for="customerEmail" class="#{!customerEmail.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                  
                    <tr class="#{!customerRegisteredBy.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="Registered By:" for="customerRegisteredBy" />
                        </td>
                        <td>
                            <h:inputText id="customerRegisteredBy" value="#{customer.registeredBy}" title="customerRegisteredBy" required="true" requiredMessage="Please enter the name of user who registered the customer " pt:placeholder="Daniel Radcliffe"/>
              
                             <br/>
                            <h:message for="customerRegisteredBy" class="#{!customerRegisteredBy.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                     <tr class="#{!customerRegisteredOn.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="Registered On:" for="customerRegisteredOn" />
                        </td>
                        <td>
                            <h:inputText id="customerRegisteredOn" value="#{customer.registeredOn}" title="customerRegisteredOn" required="true" requiredMessage="Please enter the date on which the customer is registered "  validatorMessage="Registration date entered for customer is not valid" pt:placeholder="01-11-2020">
                             <f:convertDateTime pattern = "dd-mm-yyyy" /></h:inputText>
                             <br/>
                            <h:message for="customerRegisteredOn" class="#{!customerRegisteredOn.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                
                 <tr class="#{!customerAssignee.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="Customer Assigned To:" for="customerAssignedTo" />
                        </td>
                        <td>
                            <h:inputText id="customerAssignedTo" value="#{customer.customerAssignee}" title="customerAssignedTo" required="true" requiredMessage="Please enter the name of user to whom the customer is assigned" pt:placeholder="Daniel Radcliffe"/>
                            <br/>
                            <h:message for="customerAssignedTo" class="#{!customerAssignedTo.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                
    
                
                    <tr class="#{!streetNumber.valid ? 'has-error' : 'none'}">
                        <td width ="200">
                            <h:outputLabel value="Street Number:" for="streetNumber" />
                        </td>
                        <td>
                            <h:inputText id="streetNumber" value="#{customer.streetNumber}" title="streetNumber" required="true" requiredMessage="Please enter the street number!" validatorMessage="Please enter a street number between 1 and 1000" converterMessage="Please enter a number" pt:placeholder="900">
	                            <f:convertNumber integerOnly="true"/>
								<f:validateLongRange minimum="1" maximum="1000" /> 
							</h:inputText>
                            <br/>
                            <h:message for="streetNumber" class="#{!streetNumber.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    </tr>

                    <tr class="#{!streetAddress.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="Street Address:" for="streetAddress" />
                        </td>
                        <td>
                            <h:inputText id="streetAddress" value="#{customer.streetAddress}" title="streetAddress" required="true" requiredMessage="Please enter the street address!" pt:placeholder="Dandenong Rd"/>
                            <br/>
                            <h:message for="streetAddress" class="#{!streetAddress.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    
                    <tr class="#{!suburb.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="Suburb:" for="suburb" />
                        </td>
                        <td>
                            <h:inputText id="suburb" value="#{customer.suburb}" title="suburb" required="true" requiredMessage="Please enter the suburb!" pt:placeholder="Caulfield East"/>
                        	<br/>
                            <h:message for="suburb" class="#{!suburb.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    
                    <tr class="#{!state.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="State:" for="state"/>
                        </td>
                        <td>
                            <h:inputText id="state" value="#{customer.state}" title="state" size="3" required="true" requiredMessage="Please enter the state!" pt:placeholder="VIC"/>
                            <br/>
                            <h:message for="state" class="#{!state.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    <tr class="#{!postcode.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="Postcode: " for="postcode" />
                        </td>
                        <td>
                            <h:inputText id="postcode" value="#{customer.postcode}" title="postcode" required="true" requiredMessage="Please enter the postcode!" validatorMessage="Please enter a postcode between 0200 and 4700" converterMessage="Please enter a number" pt:placeholder="3145">
	                            <f:convertNumber integerOnly="true"/>
								<f:validateLongRange minimum="200" maximum="4700" /> 
							</h:inputText>
							<br/>
							<h:message for="postcode" class="#{!postcode.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                
                    
                    <tr>
                        <td>
                            <h:outputLabel value="Number Of Products Purchased:" for="numberOfProductsPurchased"/>
                        </td>
                        <td>
                            <h:inputText id="numberOfProductsPurchased" value="#{customer.noOfProductsPurchased}" title="NumberOfProductsPurchased" required="true" requiredMessage="Please enter the number of products purchased !" validatorMessage="The number of bedrooms must be larger than or equal to 0" converterMessage="Please enter a number" pt:placeholder="4">
                        		<f:convertNumber integerOnly="true"/>
                        		<f:validateLongRange minimum="0"/> 
                           	</h:inputText>
                           	<br/>
                           	<h:message for="numberOfProductsPurchased" class="#{!numberOfProductsPurchased.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                     <tr>
							<td><h:outputLabel value="Industry Type:" for="industryType" /></td>
							<td><h:selectOneMenu id="industryType"
									value="#{customer.industryTypeName}" required="true" 
									 requiredMessage="Please select the industry type of customer !"
									 converter="#{industryType.industryTypeName}">
									<f:selectItem itemValue="#{null}" itemLabel="--select--" />
									<f:selectItems value="#{customerManagedBean.allIndustryType}"
										var="c" itemLabel="#{c.industryTypeName}" itemValue="#{c.industryTypeName}" />
								</h:selectOneMenu></td>
						</tr>
                    
          
                    
                    
                    
                </table>
                
                <h:commandButton id="submit" value="Submit" action="#{addCustomer.addCustomer(customer)}" class="btn btn-primary" >
                </h:commandButton>
                <h:link id="close" value="Close" outcome="faces/customerindex.xhtml"
						class="btn btn-primary" />
            	
            </h:form>
			
        </f:view>
            </div>
        </div>
       
    </h:body>
</html>

CMWebApp-war/WebContent/error.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
	<h:head>
		<title>Authentication Error</title>
	</h:head> 
	<body> 
		<h2>Authentication Error</h2>
        <p>The user credentials you have supplied are incorrect.</p>
        <p>Please attempt to <h:link outcome="login" value="login" /> again.</p>
	</body> 
</html>

CMWebApp-war/WebContent/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <title>#{titleController.pageTitle}</title>
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <!-- Title Customer Management-->
                <div class="navbar-brand">
                    #{titleController.pageTitle} - Customer Management Web Application
                </div>
            </div>
 
		<h2>Welcome to Customer Management Web Application!</h2>
		<br/>
		<h:link outcome="admin/index" value="Access Admin Area" />
		
	  </div>
    </h:body>
</html>